# -*- coding: utf-8 -*-
"""SinglyLinkedList.py
Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gpYLQXonvvK62YVuE9W4N2V9bXPNdzkR
"""

class Node:
  def __init__(self,data):
    self.data=data
    self.next=None
    print(f'Creating element {data}')

class LinkedList:
  def __init__(self):
    self.head=None
    self.size=0
  def add_first(self,data):
    newnode=Node(data)
    newnode.next=self.head
    self.head=newnode
    self.size+=1
  def display(self):
    if self.head is None:
      print(f'Empty')
      return
    current=self.head
    pos=0
    while current:
      print(f'element in {pos}: Data: {current.data}')
      current=current.next
      pos+=1

  def add_ending(self,data):
    newnode=Node(data)
    if self.head == None:
      self.head=newnode
      self.size +=1
    else:
      current=self.head
      while current.next:
        current=current.next
      current.next=newnode
    self.size +=1
  def add_at_position(self,data,position):
    newnode=Node(data)
    if position < 0 or position > self.size:
      print(f'position {position} is invalid')
      return
    elif position == 0:
      self.add_first(data)
      return

    current=self.head
    count=0
    while count < position -1:
      current=current.next
      count+=1
    newnode.next=current.next
    current.next=newnode
    self.size+=1

  def delete_from_beginning(self):
    if self.head is None:
      print('empty')
      return
    delete_data=self.head.data
    self.head=self.head.next
    self.size -=1
    return delete_data


llist=LinkedList()
llist.display()
llist.add_first(20)
llist.add_first(10)
llist.add_first(30)
llist.display()
llist.add_ending(50)
llist.display()
llist.add_at_position(80,2)
llist.display()
llist.delete_from_beginning()
llist.display()
